build_now:              'YES'  
download_base_url:      'http://www.your/url/to/upload/thezip/'
appcast_basefolder:     './'  
appcast_xml_name:       'appcast.xml'  
keychain_privkey_name:  'Sparkle Private Key 1'
css_file_name:          'rnotes.css' 